name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Backend smoke test
      run: |
        python -c "from minivector.embedder import Embedder; e = Embedder(); print('✓ Embedder works')"
        python -c "from minivector.vector_store import VectorStore; print('✓ VectorStore works')"

  docker-build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend Docker image
        run: docker build -t minivector-backend .

      - name: Build frontend Docker image
        run: docker build -t minivector-frontend ./frontend
